# Generated by Django 5.2.3 on 2025-07-09 14:28

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Введите название категории",
                        max_length=100,
                        unique=True,
                        verbose_name="Категория",
                    ),
                ),
            ],
            options={
                "verbose_name": "Категория",
                "verbose_name_plural": "Категории",
            },
        ),
        migrations.CreateModel(
            name="OperationType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Введите тип операции",
                        max_length=50,
                        unique=True,
                        verbose_name="Тип операции",
                    ),
                ),
            ],
            options={
                "verbose_name": "Тип операции",
                "verbose_name_plural": "Типы операций",
            },
        ),
        migrations.CreateModel(
            name="Status",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Введите статус",
                        max_length=100,
                        unique=True,
                        verbose_name="Статус движения денежных средств",
                    ),
                ),
            ],
            options={
                "verbose_name": "Статус",
                "verbose_name_plural": "Статусы",
            },
        ),
        migrations.CreateModel(
            name="Subcategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Введите подкатегорию",
                        max_length=100,
                        unique=True,
                        verbose_name="Подкатегория",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        help_text="Выберите категорию или введи вручную",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subcategory",
                        to="cashflow.category",
                        verbose_name="Категория",
                    ),
                ),
            ],
            options={
                "verbose_name": "Подкатегория",
                "verbose_name_plural": "Подкатегории",
            },
        ),
        migrations.CreateModel(
            name="CashFlow",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateField(
                        default=django.utils.timezone.now,
                        verbose_name="Дата создания записи",
                    ),
                ),
                (
                    "sum",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=15,
                        verbose_name="Сумма операции",
                    ),
                ),
                (
                    "comment",
                    models.TextField(
                        blank=True,
                        help_text="Введите комментарий",
                        null=True,
                        verbose_name="Комментарий",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        help_text="Выберите категорию или введите вручную",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cashflows",
                        to="cashflow.category",
                        verbose_name="Категория",
                    ),
                ),
                (
                    "operation_type",
                    models.ForeignKey(
                        help_text="Выберите тип операции",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="cashflow.operationtype",
                        verbose_name="Тип операции",
                    ),
                ),
                (
                    "status",
                    models.ForeignKey(
                        help_text="Выберите статус операции",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="cashflow.status",
                        verbose_name="Статус",
                    ),
                ),
                (
                    "subcategory",
                    models.ForeignKey(
                        help_text="Выберите подкатегорию или введите вручную",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="cashflow.subcategory",
                        verbose_name="Подкатегория",
                    ),
                ),
            ],
            options={
                "verbose_name": "Денежный поток",
                "verbose_name_plural": "Денежные потоки",
            },
        ),
    ]
